### ISSUE TITLE
infinited imensional functional representations

### ISSUE THREAD

**Issue by haolsun** [jinxu06/metafun-tensorflow#3]
Hi,there!
Can I ask a question about the methed itself?
It is stated that "summarising tasks with infinited dimensional functional representations" in the paper. How does this work? Is it related to the representer theorem in kernel methods in eq. (2). The rbf kernel projects the input to an infinited dimensional space. If so, this assumption of infinited dimension should be invalid for the attention-based FUNPOOLING.

Can you provide a short comment or some refs?

**Comment by jinxu06** [comment]
Hi @haolsun, thanks for the question.

By "functional representations", we mean the representations lie in function space rather than Euclidean space. And the output r() in eq2 is indeed a function (which can be queried at any point) rather than a vector. 

The representer theorem talks about the final minimizer while we are saying the reps at each iteration are in function space (Reproducing kernel Hilbert space when kernels are used, not necessarily rbf).

Attention could be seen as a deep learning version of kernels [slides](https://hyunjik11.github.io/talks/Attention_the_Analogue_of_Kernels_in_Deep_Learning.pdf).

Hope this helps!

**Comment by haolsun** [comment]
Got it! Thank you very much for the explanation.
